// <auto-generated />
using System;
using CaseStudy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseStudy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230118154612_rename")]
    partial class rename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseStudy.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Note", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Deneme not 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Deneme not 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Deneme not 3",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CaseStudy.Models.NoteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoteId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("UserId");

                    b.ToTable("NoteDetail", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Deneme not detay 1",
                            NoteId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Deneme not detay 1",
                            NoteId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Deneme not detay 1",
                            NoteId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CaseStudy.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Veli"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Cem"
                        });
                });

            modelBuilder.Entity("CaseStudy.Models.Note", b =>
                {
                    b.HasOne("CaseStudy.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseStudy.Models.NoteDetail", b =>
                {
                    b.HasOne("CaseStudy.Models.Note", "Notes")
                        .WithMany("NoteDetails")
                        .HasForeignKey("NoteId");

                    b.HasOne("CaseStudy.Models.User", "User")
                        .WithMany("NoteDetails")
                        .HasForeignKey("UserId");

                    b.Navigation("Notes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseStudy.Models.Note", b =>
                {
                    b.Navigation("NoteDetails");
                });

            modelBuilder.Entity("CaseStudy.Models.User", b =>
                {
                    b.Navigation("NoteDetails");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
